// Mocks generated by Mockito 5.4.4 from annotations
// in skinx_test/test/cubit/playlist_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:oauth2_client/access_token_response.dart' as _i6;
import 'package:skinx_test/features/authentication/data/model/user_profile_response.dart'
    as _i7;
import 'package:skinx_test/features/authentication/data/repository/spotify_authentication_repository.dart'
    as _i14;
import 'package:skinx_test/features/authentication/data/source/remote/spotify_remote_data_source.dart'
    as _i5;
import 'package:skinx_test/features/playlist/data/model/create/create_new_playlist_request.dart'
    as _i12;
import 'package:skinx_test/features/playlist/data/model/detail/playlist_detail_request.dart'
    as _i13;
import 'package:skinx_test/features/playlist/data/model/detail/playlist_detail_response.dart'
    as _i4;
import 'package:skinx_test/features/playlist/data/model/my_playlist_request.dart'
    as _i10;
import 'package:skinx_test/features/playlist/data/model/my_playlist_response.dart'
    as _i3;
import 'package:skinx_test/features/playlist/domain/entity/playlist_ui_model.dart'
    as _i2;
import 'package:skinx_test/features/playlist/domain/repository/playlist_repository.dart'
    as _i11;
import 'package:skinx_test/features/playlist/domain/usecase/get_playlist_usecase.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePlaylistModel_0 extends _i1.SmartFake implements _i2.PlaylistModel {
  _FakePlaylistModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMyPlaylistResponse_1 extends _i1.SmartFake
    implements _i3.MyPlaylistResponse {
  _FakeMyPlaylistResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlaylistDetailResponse_2 extends _i1.SmartFake
    implements _i4.PlaylistDetailResponse {
  _FakePlaylistDetailResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSpotifyRemoteDataSource_3 extends _i1.SmartFake
    implements _i5.SpotifyRemoteDataSource {
  _FakeSpotifyRemoteDataSource_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAccessTokenResponse_4 extends _i1.SmartFake
    implements _i6.AccessTokenResponse {
  _FakeAccessTokenResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserProfileResponse_5 extends _i1.SmartFake
    implements _i7.UserProfileResponse {
  _FakeUserProfileResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IGetPlaylistUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockIGetPlaylistUseCase extends _i1.Mock
    implements _i8.IGetPlaylistUseCase {
  MockIGetPlaylistUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.PlaylistModel> getPlaylist(
          {required _i10.MyPlaylistRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlaylist,
          [],
          {#request: request},
        ),
        returnValue: _i9.Future<_i2.PlaylistModel>.value(_FakePlaylistModel_0(
          this,
          Invocation.method(
            #getPlaylist,
            [],
            {#request: request},
          ),
        )),
      ) as _i9.Future<_i2.PlaylistModel>);
}

/// A class which mocks [IPlaylistRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPlaylistRepository extends _i1.Mock
    implements _i11.IPlaylistRepository {
  MockIPlaylistRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i3.MyPlaylistResponse> getPlaylist(
          {required _i10.MyPlaylistRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlaylist,
          [],
          {#request: request},
        ),
        returnValue:
            _i9.Future<_i3.MyPlaylistResponse>.value(_FakeMyPlaylistResponse_1(
          this,
          Invocation.method(
            #getPlaylist,
            [],
            {#request: request},
          ),
        )),
      ) as _i9.Future<_i3.MyPlaylistResponse>);

  @override
  _i9.Future<dynamic> createNewPlaylist(
          {required _i12.CreateNewPlaylistRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createNewPlaylist,
          [],
          {#request: request},
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<_i4.PlaylistDetailResponse> getPlaylistDetail(
          {required _i13.PlaylistDetailRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlaylistDetail,
          [],
          {#request: request},
        ),
        returnValue: _i9.Future<_i4.PlaylistDetailResponse>.value(
            _FakePlaylistDetailResponse_2(
          this,
          Invocation.method(
            #getPlaylistDetail,
            [],
            {#request: request},
          ),
        )),
      ) as _i9.Future<_i4.PlaylistDetailResponse>);
}

/// A class which mocks [SpotifyAuthenticationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpotifyAuthenticationRepository extends _i1.Mock
    implements _i14.SpotifyAuthenticationRepository {
  MockSpotifyAuthenticationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.SpotifyRemoteDataSource get spotifyDataSource => (super.noSuchMethod(
        Invocation.getter(#spotifyDataSource),
        returnValue: _FakeSpotifyRemoteDataSource_3(
          this,
          Invocation.getter(#spotifyDataSource),
        ),
      ) as _i5.SpotifyRemoteDataSource);

  @override
  _i9.Future<_i6.AccessTokenResponse> authentication() => (super.noSuchMethod(
        Invocation.method(
          #authentication,
          [],
        ),
        returnValue: _i9.Future<_i6.AccessTokenResponse>.value(
            _FakeAccessTokenResponse_4(
          this,
          Invocation.method(
            #authentication,
            [],
          ),
        )),
      ) as _i9.Future<_i6.AccessTokenResponse>);

  @override
  _i9.Future<_i7.UserProfileResponse> getUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [],
        ),
        returnValue: _i9.Future<_i7.UserProfileResponse>.value(
            _FakeUserProfileResponse_5(
          this,
          Invocation.method(
            #getUserProfile,
            [],
          ),
        )),
      ) as _i9.Future<_i7.UserProfileResponse>);

  @override
  _i9.Future<dynamic> saveUserProfile(
          {required _i7.UserProfileResponse? userProfileResponse}) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserProfile,
          [],
          {#userProfileResponse: userProfileResponse},
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);
}
